name: publish release

on:
  pull_request:
    branches: [master, main]
    types: [closed]

env:
  JAVA_VERSION: '21'
  JAVA_DISTRIBUTION: 'temurin'
  JRE_VERSION: '21.0.1'
  GITHUB_TOKEN: ${{ github.token }}
  ARTIFACT_NAME: 'FormikoLudoStore'
  USER_NAME: 'FormikoLudo'
  USER_EMAIL: 'hydrolien.f@gmail.com'
  UUID: '1468571e-011f-4fab-80e4-fa15e9b364b4'
jobs:
  releaseJob:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{ steps.version.outputs.content }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: ${{ env.JAVA_DISTRIBUTION }}
        java-version: ${{ env.JAVA_VERSION }}


    - name: Read version.md
      id: version
      uses: juliangruber/read-file-action@v1
      with:
        path: version.md

    - name: create release
      run: |
        echo "Move version.md to resources and create CHANGELOG.md if not exist"
        if (!(Test-Path "src/main/resources")) {
          mkdir src/main/resources
        }
        if (!(Test-Path "CHANGELOG*")) {
          New-Item CHANGELOG.md
        }
        mv version.md assets/
        echo "Build and move to root with desired name"
        ./gradlew assemble -Pversion='${{ steps.version.outputs.content }}'
        ls lwjgl3/build/lib/
        mv lwjgl3/build/lib/${{ env.ARTIFACT_NAME }}-${{ steps.version.outputs.content }}.jar ${{ env.ARTIFACT_NAME }}.jar
        ls

    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: true
        release_name: ${{ steps.version.outputs.content }}
        tag_name: ${{ steps.version.outputs.content }}
        body_path: CHANGELOG.md
    - name: upload .jar artifact
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.ARTIFACT_NAME}}.jar
        asset_name: ${{ env.ARTIFACT_NAME}}.jar
        asset_content_type: application/jar
    - name: LauncherJar
      uses: HydrolienF/LauncherJar@0.4.0
      with:
        project-name: ${{ env.ARTIFACT_NAME }}
        user-name: ${{ env.USER_NAME }}
        launcher-jar-version: 0.4.0
        GITHUB_TOKEN: ${{ github.token }}
        release-url: ${{ steps.create_release.outputs.upload_url }}
        app-version: ${{ steps.version.outputs.content }}
        launcher-extension: 'jar'
        JRE_VERSION: ${{ env.JRE_VERSION }}

  LauncherJar:
    name: 'LauncherJar ${{ matrix.os }} ${{ matrix.launcher-extension }}'
    strategy:
      fail-fast: false
      matrix:
        launcher-extension: [ deb, rpm, exe ]
        include:
          - launcher-extension: deb
            os: ubuntu-latest
          - launcher-extension: rpm
            os: ubuntu-latest
          - launcher-extension: exe
            os: windows-latest
    if: github.event.pull_request.merged == true
    needs: releaseJob
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: LauncherJar
      uses: HydrolienF/LauncherJar@0.4.0
      with:
        project-name: ${{ env.ARTIFACT_NAME }}
        user-name: ${{ env.USER_NAME }}
        launcher-jar-version: 0.4.0
        GITHUB_TOKEN: ${{ github.token }}
        release-url: ${{ needs.releaseJob.outputs.upload_url }}
        app-version: ${{ needs.releaseJob.outputs.version }}
        launcher-extension: ${{ matrix.launcher-extension }}
        uuid: ${{ env.UUID }}
        JRE_VERSION: ${{ env.JRE_VERSION }}
        deb-maintainer-email: ${{ env.USER_EMAIL }}